name: GitHub Actions Demo
run-name: ${{ github.actor }} 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-15
    steps:
      - run: cc ${{ github.workspace }}/main.c
      - run: ./a.out
