name: GitHub Actions Demo
run-name: ${{ github.actor }} 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-15
    steps:
      - name: explore
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
      - run: ls
      - run: clang++ --version
      - run: clang++ -std=c++23 ${{ github.workspace }}/main.cpp
      - run: ./a.out
